# Generated by Django 3.2.7 on 2021-10-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coursereg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateadded', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('college', models.TextField()),
                ('dep', models.CharField(max_length=30)),
                ('ystudy', models.CharField(max_length=10)),
                ('contact', models.BigIntegerField()),
                ('mailid', models.EmailField(max_length=200)),
                ('course', models.TextField()),
                ('note', models.TextField()),
            ],
        ),
    ]
