# Generated by Django 3.2.7 on 2021-10-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_coursereg_dateadded'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereg',
            name='chscore',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='coursereg',
            name='handson',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='coursereg',
            name='sid',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
