# Generated by Django 3.2.7 on 2021-11-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_coursereg_projrepo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereg',
            name='sid',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
