# Generated by Django 3.2.7 on 2021-11-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_alter_coursereg_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereg',
            name='cend',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='coursereg',
            name='cstart',
            field=models.DateField(null=True),
        ),
    ]
